"""
Exportar Relatório — Freenomics
Página dedicada para gerar um PDF com as secções que já visitaste noutras páginas.
Não recalcula nada: usa exatamente os dados/configurações que deixaste em cada página.
"""

import streamlit as st
import io
import sys
import os
from datetime import datetime
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from utils import show_logo
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable, PageBreak
)
from reportlab.lib.enums import TA_CENTER
from translations import CSS

st.markdown(CSS, unsafe_allow_html=True)
lang = st.session_state.get("lang", "🇵🇹 Português")

# ── TRADUÇÕES DESTA PÁGINA ────────────────────────────────────
T = {
    "🇵🇹 Português": {
        "titulo": "Exportar Relatório",
        "subtitulo": "Seleciona as secções que queres incluir. Os dados vêm diretamente do que configuraste em cada página — visita-as primeiro.",
        "secoes_titulo": "📋 Secções a incluir",
        "sec_dashboard": "📊 Análise de Carteira",
        "sec_comparador": "🔄 Comparador de Carteiras",
        "sec_simulador": "💰 Simulador de Investimento",
        "sec_risco": "⚠️ Análise de Risco",
        "sec_noticias": "📰 Notícias da Carteira",
        "sec_dividendos": "📅 Dividendos",
        "sec_patrimonio": "💎 Património",
        "btn_gerar": "📄 Gerar e descarregar relatório PDF",
        "a_gerar": "A gerar relatório...",
        "sucesso": "✅ Relatório gerado com sucesso!",
        "seleciona_uma": "Seleciona pelo menos uma secção para incluir no relatório.",
        "sem_dados": "Ainda não visitaste esta página nesta sessão — vai lá primeiro e gera os resultados.",
        "pdf_titulo": "Relatório de Investimento",
        "pdf_gerado": "Gerado por Freenomics",
        "pdf_nome": "relatorio_freenomics.pdf",
        "rodape": "Freenomics · Dados via Yahoo Finance · Não constitui aconselhamento financeiro.",
    },
    "🇬🇧 English": {
        "titulo": "Export Report",
        "subtitulo": "Select the sections to include. Data comes directly from what you configured on each page — visit them first.",
        "secoes_titulo": "📋 Sections to include",
        "sec_dashboard": "📊 Portfolio Analysis",
        "sec_comparador": "🔄 Portfolio Comparator",
        "sec_simulador": "💰 Investment Simulator",
        "sec_risco": "⚠️ Risk Analysis",
        "sec_noticias": "📰 Portfolio News",
        "sec_dividendos": "📅 Dividends",
        "sec_patrimonio": "💎 Net Worth",
        "btn_gerar": "📄 Generate and download PDF report",
        "a_gerar": "Generating report...",
        "sucesso": "✅ Report successfully generated!",
        "seleciona_uma": "Select at least one section to include in the report.",
        "sem_dados": "You haven't visited this page yet this session — go there first and generate the results.",
        "pdf_titulo": "Investment Report",
        "pdf_gerado": "Generated by Freenomics",
        "pdf_nome": "freenomics_report.pdf",
        "rodape": "Freenomics · Data via Yahoo Finance · Does not constitute financial advice.",
    },
    "🇫🇷 Français": {
        "titulo": "Exporter le Rapport",
        "subtitulo": "Sélectionnez les sections à inclure. Les données proviennent de ce que vous avez configuré sur chaque page — visitez-les d'abord.",
        "secoes_titulo": "📋 Sections à inclure",
        "sec_dashboard": "📊 Analyse de Portefeuille",
        "sec_comparador": "🔄 Comparateur",
        "sec_simulador": "💰 Simulateur",
        "sec_risco": "⚠️ Analyse des Risques",
        "sec_noticias": "📰 Actualités du Portefeuille",
        "sec_dividendos": "📅 Dividendes",
        "sec_patrimonio": "💎 Patrimoine",
        "btn_gerar": "📄 Générer et télécharger le rapport PDF",
        "a_gerar": "Génération du rapport...",
        "sucesso": "✅ Rapport généré avec succès!",
        "seleciona_uma": "Sélectionnez au moins une section.",
        "sem_dados": "Vous n'avez pas encore visité cette page — allez-y d'abord et générez les résultats.",
        "pdf_titulo": "Rapport d'Investissement",
        "pdf_gerado": "Généré par Freenomics",
        "pdf_nome": "rapport_freenomics.pdf",
        "rodape": "Freenomics · Données via Yahoo Finance · Ne constitue pas un conseil financier.",
    },
    "🇩🇪 Deutsch": {
        "titulo": "Bericht exportieren",
        "subtitulo": "Wählen Sie die gewünschten Abschnitte. Die Daten stammen direkt aus Ihren Einstellungen auf jeder Seite — besuchen Sie diese zuerst.",
        "secoes_titulo": "📋 Einzuschließende Abschnitte",
        "sec_dashboard": "📊 Portfolio-Analyse",
        "sec_comparador": "🔄 Portfolio-Vergleich",
        "sec_simulador": "💰 Investitionssimulator",
        "sec_risco": "⚠️ Risikoanalyse",
        "sec_noticias": "📰 Portfolio-Nachrichten",
        "sec_dividendos": "📅 Dividenden",
        "sec_patrimonio": "💎 Vermögen",
        "btn_gerar": "📄 PDF-Bericht erstellen und herunterladen",
        "a_gerar": "Bericht wird erstellt...",
        "sucesso": "✅ Bericht erfolgreich erstellt!",
        "seleciona_uma": "Wählen Sie mindestens einen Abschnitt aus.",
        "sem_dados": "Sie haben diese Seite in dieser Sitzung noch nicht besucht — gehen Sie zuerst dorthin.",
        "pdf_titulo": "Investitionsbericht",
        "pdf_gerado": "Erstellt von Freenomics",
        "pdf_nome": "freenomics_bericht.pdf",
        "rodape": "Freenomics · Daten via Yahoo Finance · Stellt keine Finanzberatung dar.",
    },
    "🇪🇸 Español": {
        "titulo": "Exportar Informe",
        "subtitulo": "Selecciona las secciones a incluir. Los datos vienen directamente de lo configurado en cada página — visítalas primero.",
        "secoes_titulo": "📋 Secciones a incluir",
        "sec_dashboard": "📊 Análisis de Cartera",
        "sec_comparador": "🔄 Comparador de Carteras",
        "sec_simulador": "💰 Simulador de Inversión",
        "sec_risco": "⚠️ Análisis de Riesgo",
        "sec_noticias": "📰 Noticias de la Cartera",
        "sec_dividendos": "📅 Dividendos",
        "sec_patrimonio": "💎 Patrimonio",
        "btn_gerar": "📄 Generar y descargar informe PDF",
        "a_gerar": "Generando informe...",
        "sucesso": "✅ ¡Informe generado con éxito!",
        "seleciona_uma": "Selecciona al menos una sección para incluir en el informe.",
        "sem_dados": "Todavía no has visitado esta página en esta sesión — ve primero y genera los resultados.",
        "pdf_titulo": "Informe de Inversión",
        "pdf_gerado": "Generado por Freenomics",
        "pdf_nome": "informe_freenomics.pdf",
        "rodape": "Freenomics · Datos via Yahoo Finance · No constituye asesoramiento financiero.",
    },
}[lang]

# ── CABEÇALHO ────────────────────────────────────────────────
show_logo()
st.title(T["titulo"])
st.caption(T["subtitulo"])

# ── SECÇÕES ──────────────────────────────────────────────────
st.header(T["secoes_titulo"])

disponiveis = {
    "dashboard":   ("export_dashboard",   T["sec_dashboard"]),
    "comparador":  ("export_comparador",  T["sec_comparador"]),
    "simulador":   ("export_simulador",   T["sec_simulador"]),
    "risco":       ("export_risco",       T["sec_risco"]),
    "dividendos":  ("export_dividendos",  T["sec_dividendos"]),
    "patrimonio":  ("export_patrimonio",  T["sec_patrimonio"]),
    "noticias":    ("export_noticias",    T["sec_noticias"]),
}

selecionadas = {}
itens = list(disponiveis.items())
for inicio in range(0, len(itens), 4):
    bloco = itens[inicio:inicio+4]
    cols = st.columns(len(bloco))
    for col, (chave, (session_key, label)) in zip(cols, bloco):
        disponivel = session_key in st.session_state
        with col:
            marcado = st.checkbox(label, value=disponivel, disabled=not disponivel)
            if disponivel and marcado:
                selecionadas[chave] = st.session_state[session_key]
            if not disponivel:
                st.caption(f"ℹ️ {T['sem_dados']}")

st.markdown("---")

# ── GERADOR DE PDF ───────────────────────────────────────────
def gerar_pdf_completo(secoes):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    AZUL    = colors.HexColor("#0E2A3D")
    DOURADO = colors.HexColor("#C29A4B")
    CREME   = colors.HexColor("#FAF8F3")
    CINZA   = colors.HexColor("#6B7280")

    e_capa    = ParagraphStyle("capa",   fontSize=28, textColor=AZUL,   fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=8)
    e_subcapa = ParagraphStyle("scapa",  fontSize=11, textColor=CINZA,  fontName="Helvetica",      alignment=TA_CENTER, spaceAfter=4)
    e_h1      = ParagraphStyle("h1",     fontSize=16, textColor=AZUL,   fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=6)
    e_h2      = ParagraphStyle("h2",     fontSize=12, textColor=AZUL,   fontName="Helvetica-Bold", spaceBefore=8,  spaceAfter=4)
    e_corpo   = ParagraphStyle("corpo",  fontSize=9,  textColor=colors.HexColor("#2A2A2A"),
                               fontName="Helvetica", leading=14, spaceAfter=5)
    e_aviso   = ParagraphStyle("aviso",  fontSize=7,  textColor=CINZA,  fontName="Helvetica-Oblique", leading=11)

    el = []

    # ── CAPA ──
    el.append(Spacer(1, 3*cm))
    el.append(Paragraph("📊 Freenomics", e_subcapa))
    el.append(Spacer(1, 0.5*cm))
    el.append(Paragraph(T["pdf_titulo"], e_capa))
    el.append(Spacer(1, 0.5*cm))
    el.append(HRFlowable(width="60%", thickness=3, color=DOURADO, hAlign="CENTER"))
    el.append(Spacer(1, 0.5*cm))
    el.append(Paragraph(f"{T['pdf_gerado']} · {datetime.today().strftime('%d/%m/%Y')}", e_subcapa))
    secs_incluidas = [label for k, (_, label) in disponiveis.items() if k in secoes]
    el.append(Paragraph(" · ".join(secs_incluidas), e_subcapa))
    el.append(PageBreak())

    import re
    def limpar_md(texto):
        return re.sub(r"\*\*(.*?)\*\*", r"\1", texto)

    def tabela_metricas(dados_metricas, labels):
        cab = ["Ativo"] + labels
        linhas = [cab]
        for t, m in dados_metricas.items():
            linhas.append([t, f"{m['retorno_total']}%", f"{m['volatilidade']}%",
                          f"{m['max_drawdown']}%", str(m['sharpe'])])
        tab = Table(linhas, colWidths=[3.5*cm, 3.5*cm, 3.5*cm, 3.5*cm, 3*cm])
        tab.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),AZUL), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),9),
            ("ALIGN",(0,0),(-1,-1),"CENTER"), ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[CREME,colors.white]),
            ("FONTNAME",(0,1),(-1,-1),"Helvetica"),
            ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#E5DFD0")),
            ("TOPPADDING",(0,0),(-1,-1),6), ("BOTTOMPADDING",(0,0),(-1,-1),6),
            ("LEFTPADDING",(0,0),(-1,-1),8), ("RIGHTPADDING",(0,0),(-1,-1),8),
            ("LINEBELOW",(0,0),(-1,0),1.5,DOURADO),
        ]))
        return tab

    def add_secao_titulo(titulo):
        el.append(HRFlowable(width="100%", thickness=2, color=DOURADO))
        el.append(Spacer(1, 0.2*cm))
        el.append(Paragraph(titulo, e_h1))
        el.append(Spacer(1, 0.2*cm))

    def add_insight(texto):
        if not texto:
            return
        for paragrafo in limpar_md(texto).split("\n\n"):
            if paragrafo.strip():
                el.append(Paragraph(paragrafo.strip(), e_corpo))
        el.append(Spacer(1, 0.3*cm))

    # ── SECÇÃO DASHBOARD ──
    if "dashboard" in secoes:
        add_secao_titulo(T["sec_dashboard"])
        dash = secoes["dashboard"]
        if dash.get("periodo_label"):
            el.append(Paragraph(f"Período: {dash['periodo_label']}", e_h2))
        labels = ["Retorno", "Volatilidade", "Max Drawdown", "Sharpe"]
        el.append(tabela_metricas(dash["metricas"], labels))
        el.append(Spacer(1, 0.4*cm))
        add_insight(dash["insight"])
        if len(secoes) > 1:
            el.append(PageBreak())

    # ── SECÇÃO COMPARADOR ──
    if "comparador" in secoes:
        add_secao_titulo(T["sec_comparador"])
        comp = secoes["comparador"]
        if comp.get("periodo_label"):
            el.append(Paragraph(f"Período: {comp['periodo_label']}", e_h2))
        portfolios = comp.get("portfolios", [])
        if portfolios:
            cab = ["", "Retorno", "Volatilidade", "Max Drawdown", "Sharpe"]
            linhas_c = [cab]
            for p in portfolios:
                m = p["metricas"]
                linhas_c.append([p["nome"], f"{m['retorno']}%", f"{m['vol']}%",
                                  f"{m['dd']}%", str(m['sharpe'])])
            # Larguras dinâmicas: primeira coluna maior, restantes divididas pelo espaço disponível (17cm úteis em A4)
            largura_nome = 5*cm
            largura_resto = (17*cm - largura_nome) / 4
            tab_c = Table(linhas_c, colWidths=[largura_nome] + [largura_resto]*4)
            tab_c.setStyle(TableStyle([
                ("BACKGROUND",(0,0),(-1,0),AZUL), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
                ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),9),
                ("ALIGN",(0,0),(-1,-1),"CENTER"), ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[CREME,colors.white]),
                ("FONTNAME",(0,1),(-1,-1),"Helvetica"),
                ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#E5DFD0")),
                ("TOPPADDING",(0,0),(-1,-1),6), ("BOTTOMPADDING",(0,0),(-1,-1),6),
                ("LEFTPADDING",(0,0),(-1,-1),6), ("RIGHTPADDING",(0,0),(-1,-1),6),
                ("LINEBELOW",(0,0),(-1,0),1.5,DOURADO),
            ]))
            el.append(tab_c)
            el.append(Spacer(1, 0.4*cm))
        add_insight(comp.get("insight"))
        if "simulador" in secoes or "risco" in secoes or "noticias" in secoes or "dividendos" in secoes or "patrimonio" in secoes:
            el.append(PageBreak())

    # ── SECÇÃO SIMULADOR ──
    if "simulador" in secoes:
        add_secao_titulo(T["sec_simulador"])
        sim = secoes["simulador"]
        dados_sim = [
            ["Parâmetro", "Valor"],
            ["Investimento inicial", f"€{sim['inv_inicial']:,.0f}"],
            ["Contribuição mensal", f"€{sim['contrib']:,.0f}"],
            ["Horizonte temporal", f"{sim['anos']} anos"],
            ["Retorno anual esperado", f"{sim['retorno']}%"],
            ["Inflação estimada", f"{sim['inflacao']}%"],
            ["", ""],
            ["Total investido", f"€{sim['total_inv']:,.0f}"],
            ["Valor final (nominal)", f"€{sim['valor_final']:,.0f}"],
            ["Valor final (real, adj. inflação)", f"€{sim['valor_real']:,.0f}"],
            ["Ganhos via juro composto", f"€{sim['ganho']:,.0f}"],
            ["Multiplicador", f"{sim['multiplicador']:.1f}x"],
        ]
        tab_s = Table(dados_sim, colWidths=[9*cm, 8*cm])
        tab_s.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),AZUL), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),9),
            ("ALIGN",(1,0),(1,-1),"CENTER"), ("ALIGN",(0,0),(0,-1),"LEFT"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[CREME,colors.white]),
            ("FONTNAME",(0,1),(-1,-1),"Helvetica"),
            ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#E5DFD0")),
            ("TOPPADDING",(0,0),(-1,-1),6), ("BOTTOMPADDING",(0,0),(-1,-1),6),
            ("LEFTPADDING",(0,0),(-1,-1),8), ("RIGHTPADDING",(0,0),(-1,-1),8),
            ("FONTNAME",(0,7),(-1,-1),"Helvetica-Bold"),
            ("LINEBELOW",(0,0),(-1,0),1.5,DOURADO),
            ("LINEABOVE",(0,7),(-1,7),1,DOURADO),
        ]))
        el.append(tab_s)
        el.append(Spacer(1, 0.4*cm))
        add_insight(sim["insight"])
        if "risco" in secoes or "dividendos" in secoes or "patrimonio" in secoes or "noticias" in secoes:
            el.append(PageBreak())

    # ── SECÇÃO RISCO ──
    if "risco" in secoes:
        add_secao_titulo(T["sec_risco"])
        risco = secoes["risco"]
        capital = risco["capital"]
        el.append(Paragraph("Volatilidade e Value at Risk", e_h2))
        dados_r = [["Ativo", "Volatilidade Anual", "VaR 95%/dia", "Nível de risco"]]
        for t, m in risco["metricas"].items():
            nivel = "Alto" if m["vol"] > 40 else ("Médio" if m["vol"] > 20 else "Baixo")
            dados_r.append([t, f"{m['vol']:.1f}%", f"{m['var']:.2f}%", nivel])
        tab_r = Table(dados_r, colWidths=[4*cm, 4.5*cm, 4.5*cm, 4*cm])
        tab_r.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),AZUL), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),9),
            ("ALIGN",(0,0),(-1,-1),"CENTER"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[CREME,colors.white]),
            ("FONTNAME",(0,1),(-1,-1),"Helvetica"),
            ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#E5DFD0")),
            ("TOPPADDING",(0,0),(-1,-1),6), ("BOTTOMPADDING",(0,0),(-1,-1),6),
            ("LEFTPADDING",(0,0),(-1,-1),8), ("RIGHTPADDING",(0,0),(-1,-1),8),
            ("LINEBELOW",(0,0),(-1,0),1.5,DOURADO),
        ]))
        el.append(tab_r)
        el.append(Spacer(1, 0.3*cm))
        el.append(Paragraph("Cenários de Stress", e_h2))
        cenarios = {"Correção leve (-10%)": -0.10, "Correção moderada (-20%)": -0.20,
                    "Bear market (-35%)": -0.35, "Crash severo (-50%)": -0.50}
        dados_stress = [["Cenário", "Capital restante", "Perda estimada"]]
        for nome, pct in cenarios.items():
            dados_stress.append([nome, f"€{capital*(1+pct):,.0f}", f"€{capital*pct:,.0f}"])
        tab_stress = Table(dados_stress, colWidths=[6*cm, 5.5*cm, 5.5*cm])
        tab_stress.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),AZUL), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),9),
            ("ALIGN",(0,0),(-1,-1),"CENTER"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[CREME,colors.white]),
            ("FONTNAME",(0,1),(-1,-1),"Helvetica"),
            ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#E5DFD0")),
            ("TOPPADDING",(0,0),(-1,-1),6), ("BOTTOMPADDING",(0,0),(-1,-1),6),
            ("LEFTPADDING",(0,0),(-1,-1),8), ("RIGHTPADDING",(0,0),(-1,-1),8),
            ("LINEBELOW",(0,0),(-1,0),1.5,DOURADO),
        ]))
        el.append(tab_stress)
        el.append(Spacer(1, 0.4*cm))
        add_insight(risco["insight"])
        if "dividendos" in secoes or "patrimonio" in secoes or "noticias" in secoes:
            el.append(PageBreak())

    # ── SECÇÃO DIVIDENDOS ──
    if "dividendos" in secoes:
        add_secao_titulo(T["sec_dividendos"])
        div = secoes["dividendos"]
        if div.get("anos"):
            el.append(Paragraph(f"Histórico considerado: {div['anos']} anos", e_h2))
        dados_d = [["Ativo", "Dividend Yield", "Valor por ação/ano"]]
        for t, m in div["tickers"].items():
            dados_d.append([t, f"{m['yield']}%", f"${m['rate']}"])
        tab_d = Table(dados_d, colWidths=[5.5*cm, 5.5*cm, 5.5*cm])
        tab_d.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),AZUL), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),9),
            ("ALIGN",(0,0),(-1,-1),"CENTER"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[CREME,colors.white]),
            ("FONTNAME",(0,1),(-1,-1),"Helvetica"),
            ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#E5DFD0")),
            ("TOPPADDING",(0,0),(-1,-1),6), ("BOTTOMPADDING",(0,0),(-1,-1),6),
            ("LEFTPADDING",(0,0),(-1,-1),8), ("RIGHTPADDING",(0,0),(-1,-1),8),
            ("LINEBELOW",(0,0),(-1,0),1.5,DOURADO),
        ]))
        el.append(tab_d)
        el.append(Spacer(1, 0.4*cm))
        if "patrimonio" in secoes or "noticias" in secoes:
            el.append(PageBreak())

    # ── SECÇÃO PATRIMÓNIO ──
    if "patrimonio" in secoes:
        add_secao_titulo(T["sec_patrimonio"])
        pat = secoes["patrimonio"]
        if pat.get("data"):
            el.append(Paragraph(f"Calculado em: {pat['data']}", e_h2))
        dados_p = [["Categoria", "Valor"]]
        for nome, valor in pat.get("categorias", []):
            dados_p.append([nome, f"€{valor:,.0f}"])
        dados_p.append(["", ""])
        dados_p.append(["Total de Ativos", f"€{pat['total_ativos']:,.0f}"])
        dados_p.append(["Total de Passivos", f"€{pat['total_passivos']:,.0f}"])
        dados_p.append(["Património Líquido", f"€{pat['patrimonio']:,.0f}"])
        tab_p = Table(dados_p, colWidths=[9*cm, 8*cm])
        tab_p.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),AZUL), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),9),
            ("ALIGN",(1,0),(1,-1),"CENTER"), ("ALIGN",(0,0),(0,-1),"LEFT"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[CREME,colors.white]),
            ("FONTNAME",(0,1),(-1,-1),"Helvetica"),
            ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#E5DFD0")),
            ("TOPPADDING",(0,0),(-1,-1),6), ("BOTTOMPADDING",(0,0),(-1,-1),6),
            ("LEFTPADDING",(0,0),(-1,-1),8), ("RIGHTPADDING",(0,0),(-1,-1),8),
            ("FONTNAME",(0,-1),(-1,-1),"Helvetica-Bold"),
            ("LINEBELOW",(0,0),(-1,0),1.5,DOURADO),
            ("LINEABOVE",(0,-1),(-1,-1),1,DOURADO),
        ]))
        el.append(tab_p)
        el.append(Spacer(1, 0.4*cm))
        if "noticias" in secoes:
            el.append(PageBreak())

    # ── SECÇÃO NOTÍCIAS ──
    if "noticias" in secoes:
        add_secao_titulo(T["sec_noticias"])
        e_noticia_titulo = ParagraphStyle("nt", fontSize=10, textColor=AZUL,
                                          fontName="Helvetica-Bold", spaceAfter=2, spaceBefore=8)
        e_noticia_meta   = ParagraphStyle("nm", fontSize=7, textColor=CINZA,
                                          fontName="Helvetica-Oblique", spaceAfter=2)
        e_noticia_resumo = ParagraphStyle("nr", fontSize=8, textColor=colors.HexColor("#2A2A2A"),
                                          fontName="Helvetica", leading=12, spaceAfter=4)
        for ticker, artigos in secoes["noticias"].items():
            el.append(Paragraph(f"● {ticker}", ParagraphStyle("tb", fontSize=11, textColor=DOURADO,
                                fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=4)))
            el.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5DFD0")))
            for a in artigos:
                el.append(Paragraph(a["titulo"], e_noticia_titulo))
                meta = f"{a['fonte']}  ·  {a['data']}" if a["fonte"] or a["data"] else ""
                if meta:
                    el.append(Paragraph(meta, e_noticia_meta))
                if a["resumo"]:
                    el.append(Paragraph(a["resumo"] + "...", e_noticia_resumo))
            el.append(Spacer(1, 0.3*cm))

    # ── RODAPÉ ──
    el.append(Spacer(1, 0.5*cm))
    el.append(HRFlowable(width="100%", thickness=1, color=DOURADO))
    el.append(Spacer(1, 0.3*cm))
    el.append(Paragraph(T["rodape"], e_aviso))

    doc.build(el)
    buffer.seek(0)
    return buffer

# ── BOTÃO GERAR ──────────────────────────────────────────────
if st.button(T["btn_gerar"], use_container_width=True, type="primary"):
    if not selecionadas:
        st.error(T["seleciona_uma"])
        st.stop()

    with st.status(T["a_gerar"], expanded=False) as status:
        pdf = gerar_pdf_completo(selecionadas)
        status.update(label=T["sucesso"], state="complete")

    st.download_button(
        label=T["btn_gerar"],
        data=pdf,
        file_name=T["pdf_nome"],
        mime="application/pdf",
        use_container_width=True,
    )

st.markdown("---")
st.caption(T["rodape"])
